"""
shushhh key server — .onion identity and key distribution

Endpoints:
    POST /register          — Create a new user account
    POST /auth              — Authenticate and return Ed25519-signed token
    POST /upload_key        — Upload public keys for a username (requires auth signature)
    GET  /get_key/<user>    — Retrieve public keys for a specific username

This server holds usernames, password hashes, and public keys. It does NOT hold
any messages or private keys.
"""

import os
import sys
import time
import hmac
import hashlib
import sqlite3
import base64
import json
import uuid
from functools import wraps

from flask import Flask, request, jsonify, g
import nacl.signing
import nacl.encoding

app = Flask(__name__)

# ============================================================
# Configuration
# ============================================================

DATABASE = os.environ.get("SHUSHHH_KEYDB", "keyserver.db")
KEY_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "server_key.bin")

# ============================================================
# Ed25519 server signing key
# ============================================================

_signing_key = None

def load_signing_key():
    """Load the Ed25519 private key generated by setup_keys.py."""
    global _signing_key
    if not os.path.exists(KEY_FILE):
        print(f"[-] Server key not found at {KEY_FILE}")
        print("    Run setup_keys.py first to generate the keypair")
        sys.exit(1)
    with open(KEY_FILE, "rb") as f:
        key_bytes = f.read()
    _signing_key = nacl.signing.SigningKey(key_bytes)
    pub_hex = _signing_key.verify_key.encode(nacl.encoding.HexEncoder).decode()
    print(f"[+] Key Server Ed25519 public key: {pub_hex}")

def sign_payload(payload: str) -> str:
    """Sign a payload string with the server's Ed25519 key. Returns base64 signature."""
    sig = _signing_key.sign(payload.encode(), encoder=nacl.encoding.RawEncoder)
    return base64.b64encode(sig.signature).decode()

def verify_payload(payload: str, signature_b64: str) -> bool:
    """Verify an auth signature provided by the client (which we previously signed)."""
    try:
        sig_bytes = base64.b64decode(signature_b64)
        _signing_key.verify_key.verify(payload.encode(), sig_bytes)
        return True
    except Exception:
        return False

# ============================================================
# Database
# ============================================================

def get_db():
    if "db" not in g:
        g.db = sqlite3.connect(DATABASE)
        g.db.row_factory = sqlite3.Row
    return g.db

@app.teardown_appcontext
def close_db(exception):
    db = g.pop("db", None)
    if db is not None:
        db.close()

def init_db():
    db = sqlite3.connect(DATABASE)

    # User credentials table
    db.execute("""
        CREATE TABLE IF NOT EXISTS app_config (
            config_key    TEXT PRIMARY KEY,
            config_salt   TEXT NOT NULL,
            config_value  TEXT NOT NULL
        )
    """)

    # User public keys table
    db.execute("""
        CREATE TABLE IF NOT EXISTS user_keys (
            username      TEXT PRIMARY KEY,
            public_keys   TEXT NOT NULL,
            updated_at    INTEGER NOT NULL
        )
    """)

    db.commit()
    db.close()
    print("[+] Database initialized")

# ============================================================
# Endpoints
# ============================================================

@app.route("/register", methods=["POST"])
def register():
    """
    Register a new user account.
    Expects: { "username": "...", "credential_hash": "base64..." }
    """
    data = request.get_json(silent=True)
    if not data or "username" not in data or "credential_hash" not in data:
        return jsonify({"status": "error", "message": "missing fields"}), 400

    username = data["username"]
    cred_hash_b64 = data["credential_hash"]

    db = get_db()
    existing = db.execute("SELECT 1 FROM app_config WHERE config_key = ?", (username,)).fetchone()
    if existing:
        return jsonify({"status": "error", "message": "username already taken"}), 409

    salt = os.urandom(32)
    salt_hex = salt.hex()

    try:
        cred_hash = base64.b64decode(cred_hash_b64)
    except Exception:
        return jsonify({"status": "error", "message": "invalid credential hash"}), 400

    salted = hashlib.sha256(cred_hash + salt).hexdigest()

    db.execute(
        "INSERT INTO app_config (config_key, config_salt, config_value) VALUES (?, ?, ?)",
        (username, salt_hex, salted)
    )
    db.commit()

    return jsonify({"status": "ok", "message": "registered"})

@app.route("/auth", methods=["POST"])
def auth():
    """
    Authenticate a user.
    Expects: { "username": "...", "credential_hash": "base64..." }
    Returns: { "status": "ok", "payload": "...", "signature": "base64..." }
    """
    data = request.get_json(silent=True)
    if not data or "username" not in data or "credential_hash" not in data:
        return jsonify({"status": "error", "message": "missing fields"}), 400

    username = data["username"]
    cred_hash_b64 = data["credential_hash"]

    db = get_db()
    row = db.execute("SELECT config_salt, config_value FROM app_config WHERE config_key = ?", (username,)).fetchone()

    if not row:
        return jsonify({"status": "error", "message": "authentication failed"}), 401

    try:
        cred_hash = base64.b64decode(cred_hash_b64)
    except Exception:
        return jsonify({"status": "error", "message": "invalid credential"}), 400

    salt = bytes.fromhex(row["config_salt"])
    computed = hashlib.sha256(cred_hash + salt).hexdigest()

    if not hmac.compare_digest(computed, row["config_value"]):
        return jsonify({"status": "error", "message": "authentication failed"}), 401

    # Issue token (signed payload)
    payload = json.dumps({
        "username": username,
        "timestamp": int(time.time()),
        "nonce": uuid.uuid4().hex
    })
    signature = sign_payload(payload)

    return jsonify({
        "status": "ok",
        "payload": payload,
        "signature": signature
    })

@app.route("/upload_key", methods=["POST"])
def upload_key():
    """
    Upload public keys for a user.
    Expects: { "payload": "...", "signature": "...", "public_keys": "json string of keys" }
    """
    data = request.get_json(silent=True)
    if not data or "payload" not in data or "signature" not in data or "public_keys" not in data:
        return jsonify({"status": "error", "message": "missing auth or keys"}), 400

    payload = data["payload"]
    signature = data["signature"]
    public_keys = data["public_keys"]

    if not verify_payload(payload, signature):
        return jsonify({"status": "error", "message": "invalid auth signature"}), 401

    try:
        parsed_payload = json.loads(payload)
        username = parsed_payload["username"]
        # Check token expiration (e.g., 24 hours)
        if time.time() - parsed_payload["timestamp"] > 86400:
            return jsonify({"status": "error", "message": "token expired"}), 401
    except Exception:
        return jsonify({"status": "error", "message": "invalid payload"}), 400

    db = get_db()
    db.execute(
        "INSERT OR REPLACE INTO user_keys (username, public_keys, updated_at) VALUES (?, ?, ?)",
        (username, public_keys, int(time.time()))
    )
    db.commit()

    return jsonify({"status": "ok", "message": "keys uploaded"})

@app.route("/get_key/<username>", methods=["GET"])
def get_key(username):
    """
    Retrieve public keys for a specific username.
    """
    db = get_db()
    row = db.execute("SELECT public_keys FROM user_keys WHERE username = ?", (username,)).fetchone()

    if not row:
        return jsonify({"status": "error", "message": "keys not found"}), 404

    return jsonify({"status": "ok", "public_keys": row["public_keys"]})


if __name__ == "__main__":
    print()
    print("=" * 50)
    print("  shushhh KEY SERVER")
    print("  Handles identity and key distribution")
    print("=" * 50)
    print()

    load_signing_key()
    init_db()

    print("[+] Starting Key Server on 127.0.0.1:5000")
    app.run(host="127.0.0.1", port=5000, debug=False)
