"""
shushhh relay server — .onion store-and-forward relay

Endpoints:
    POST /register  — Create a new user account
    POST /auth      — Authenticate and return Ed25519-signed token
    POST /drop      — Store encrypted blob for a recipient
    GET  /fetch     — Retrieve pending messages for a recipient tag
    POST /ack       — Confirm delivery, hard-delete message

The server is cryptographically blind — it never holds session keys
and cannot decrypt any message payload. All it sees are opaque
ciphertext blobs and hashed routing tags.

Storage schema is deliberately disguised as analytics telemetry.
"""

import os
import sys
import uuid
import time
import hmac
import hashlib
import sqlite3
import base64
import json
from functools import wraps

from flask import Flask, request, jsonify, g
import nacl.signing
import nacl.encoding

app = Flask(__name__)

# ============================================================
# Configuration
# ============================================================

DATABASE = os.environ.get("SHUSHHH_DB", "telemetry.db")
KEY_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "server_key.bin")
TTL_SECONDS = 7 * 24 * 3600  # 7 days — messages auto-expire

# ============================================================
# Ed25519 server signing key
# ============================================================

_signing_key = None

def load_signing_key():
    """Load the Ed25519 private key generated by setup_keys.py."""
    global _signing_key
    if not os.path.exists(KEY_FILE):
        print(f"[-] Server key not found at {KEY_FILE}")
        print("    Run setup_keys.py first to generate the keypair")
        sys.exit(1)
    with open(KEY_FILE, "rb") as f:
        key_bytes = f.read()
    _signing_key = nacl.signing.SigningKey(key_bytes)
    pub_hex = _signing_key.verify_key.encode(nacl.encoding.HexEncoder).decode()
    print(f"[+] Server Ed25519 public key: {pub_hex}")

def sign_payload(payload: str) -> str:
    """Sign a payload string with the server's Ed25519 key. Returns base64 signature."""
    sig = _signing_key.sign(payload.encode(), encoder=nacl.encoding.RawEncoder)
    # sig.signature is the 64-byte detached signature
    return base64.b64encode(sig.signature).decode()

# ============================================================
# Database
# ============================================================

def get_db():
    """Get a database connection for the current request."""
    if "db" not in g:
        g.db = sqlite3.connect(DATABASE)
        g.db.row_factory = sqlite3.Row
    return g.db

@app.teardown_appcontext
def close_db(exception):
    db = g.pop("db", None)
    if db is not None:
        db.close()

def init_db():
    """Initialize the database with the disguised schema."""
    db = sqlite3.connect(DATABASE)

    # Disguised as analytics telemetry — plausible deniability
    db.execute("""
        CREATE TABLE IF NOT EXISTS telemetry_events (
            event_id          TEXT PRIMARY KEY,
            device_fingerprint TEXT NOT NULL,
            payload           BLOB NOT NULL,
            ts                INTEGER NOT NULL,
            ttl               INTEGER DEFAULT 604800
        )
    """)

    # User credentials table — also disguised
    db.execute("""
        CREATE TABLE IF NOT EXISTS app_config (
            config_key    TEXT PRIMARY KEY,
            config_salt   TEXT NOT NULL,
            config_value  TEXT NOT NULL
        )
    """)

    # Index for fast lookup by recipient tag
    db.execute("""
        CREATE INDEX IF NOT EXISTS idx_device_fp
        ON telemetry_events(device_fingerprint)
    """)

    db.commit()
    db.close()
    print("[+] Database initialized")

# ============================================================
# Helpers
# ============================================================

def cleanup_expired():
    """Remove messages older than TTL. Called periodically on fetch."""
    db = get_db()
    cutoff = int(time.time()) - TTL_SECONDS
    db.execute("DELETE FROM telemetry_events WHERE ts < ?", (cutoff,))
    db.commit()

# ============================================================
# Endpoints
# ============================================================

@app.route("/register", methods=["POST"])
def register():
    """
    Register a new user account.
    Expects: { "username": "...", "credential_hash": "base64..." }
    Stores: (username, random_salt, SHA-256(credential_hash + salt))
    """
    data = request.get_json(silent=True)
    if not data or "username" not in data or "credential_hash" not in data:
        return jsonify({"status": "error", "message": "missing fields"}), 400

    username = data["username"]
    cred_hash_b64 = data["credential_hash"]

    db = get_db()

    # Check if username already exists
    existing = db.execute(
        "SELECT 1 FROM app_config WHERE config_key = ?", (username,)
    ).fetchone()
    if existing:
        return jsonify({"status": "error", "message": "username already taken"}), 409

    # Generate a random salt
    salt = os.urandom(32)
    salt_hex = salt.hex()

    # Decode the credential hash from base64
    try:
        cred_hash = base64.b64decode(cred_hash_b64)
    except Exception:
        return jsonify({"status": "error", "message": "invalid credential hash"}), 400

    # Store SHA-256(credential_hash + salt) — never the raw hash
    salted = hashlib.sha256(cred_hash + salt).hexdigest()

    db.execute(
        "INSERT INTO app_config (config_key, config_salt, config_value) VALUES (?, ?, ?)",
        (username, salt_hex, salted)
    )
    db.commit()

    return jsonify({"status": "ok", "message": "registered"})

@app.route("/auth", methods=["POST"])
def auth():
    """
    Authenticate a user.
    Expects: { "username": "...", "credential_hash": "base64..." }
    Returns: { "status": "ok", "payload": "...", "signature": "base64..." }
    """
    data = request.get_json(silent=True)
    if not data or "username" not in data or "credential_hash" not in data:
        return jsonify({"status": "error", "message": "missing fields"}), 400

    username = data["username"]
    cred_hash_b64 = data["credential_hash"]

    db = get_db()
    row = db.execute(
        "SELECT config_salt, config_value FROM app_config WHERE config_key = ?",
        (username,)
    ).fetchone()

    if not row:
        return jsonify({"status": "error", "message": "authentication failed"}), 401

    stored_salt_hex = row["config_salt"]
    stored_hash = row["config_value"]

    # Decode credential hash from base64
    try:
        cred_hash = base64.b64decode(cred_hash_b64)
    except Exception:
        return jsonify({"status": "error", "message": "invalid credential"}), 400

    # Recompute: SHA-256(credential_hash + salt)
    salt = bytes.fromhex(stored_salt_hex)
    computed = hashlib.sha256(cred_hash + salt).hexdigest()

    # Constant-time comparison — prevents timing-based credential enumeration
    if not hmac.compare_digest(computed, stored_hash):
        return jsonify({"status": "error", "message": "authentication failed"}), 401

    # Build signed response payload
    payload = json.dumps({
        "username": username,
        "timestamp": int(time.time()),
        "nonce": uuid.uuid4().hex
    })
    signature = sign_payload(payload)

    return jsonify({
        "status": "ok",
        "payload": payload,
        "signature": signature
    })

@app.route("/drop", methods=["POST"])
def drop():
    """
    Store an encrypted message blob for a recipient.
    Expects: { "tag": "hex_sha256_of_recipient_pubkey", "blob": "encrypted_json" }
    """
    data = request.get_json(silent=True)
    if not data or "tag" not in data or "blob" not in data:
        return jsonify({"status": "error", "message": "missing fields"}), 400

    tag = data["tag"]
    blob = data["blob"]
    event_id = uuid.uuid4().hex
    timestamp = int(time.time())

    db = get_db()
    db.execute(
        "INSERT INTO telemetry_events (event_id, device_fingerprint, payload, ts) "
        "VALUES (?, ?, ?, ?)",
        (event_id, tag, blob, timestamp)
    )
    db.commit()

    return jsonify({"status": "ok", "event_id": event_id})

@app.route("/fetch", methods=["GET"])
def fetch():
    """
    Retrieve pending messages for a recipient tag.
    Expects query param: ?tag=hex_sha256_of_pubkey
    Returns: { "status": "ok", "messages": [ { "event_id": "...", "blob": "..." }, ... ] }
    """
    tag = request.args.get("tag")
    if not tag:
        return jsonify({"status": "error", "message": "missing tag parameter"}), 400

    # Clean up expired messages on each fetch
    cleanup_expired()

    db = get_db()
    rows = db.execute(
        "SELECT event_id, payload FROM telemetry_events "
        "WHERE device_fingerprint = ? ORDER BY ts ASC",
        (tag,)
    ).fetchall()

    messages = [{"event_id": row["event_id"], "blob": row["payload"]} for row in rows]

    return jsonify({"status": "ok", "messages": messages})

@app.route("/ack", methods=["POST"])
def ack():
    """
    Confirm delivery — hard-delete a message from the server.
    Expects: { "event_id": "..." }
    """
    data = request.get_json(silent=True)
    if not data or "event_id" not in data:
        return jsonify({"status": "error", "message": "missing event_id"}), 400

    event_id = data["event_id"]

    db = get_db()
    cursor = db.execute(
        "DELETE FROM telemetry_events WHERE event_id = ?", (event_id,)
    )
    db.commit()

    if cursor.rowcount > 0:
        return jsonify({"status": "ok", "message": "deleted"})
    else:
        return jsonify({"status": "ok", "message": "not found"})

# ============================================================
# Entry point
# ============================================================

if __name__ == "__main__":
    print()
    print("=" * 50)
    print("  shushhh relay server")
    print("  .onion store-and-forward relay")
    print("=" * 50)
    print()

    # Load server signing key
    load_signing_key()

    # Initialize database
    init_db()

    # Run on localhost:5000 — Tor hidden service config maps .onion to this
    # In production, bind to 127.0.0.1 only (Tor handles external access)
    print("[+] Starting relay on 127.0.0.1:5000")
    print("    Configure Tor hidden service to point to this address")
    print()
    app.run(host="127.0.0.1", port=5000, debug=False)
