#include "auth/auth.h"
#include "crypto/crypto.h"

#include <sodium.h>
#include <curl/curl.h>
#include <nlohmann/json.hpp>

#include <iostream>
#include <cstring>
#include <fstream>
#include <sstream>

#ifdef _WIN32
#include <windows.h>  // For password masking on Windows
#else
#include <termios.h>
#include <unistd.h>
#endif

using json = nlohmann::json;

// ============================================================
// Server Ed25519 public key — hardcoded trust anchor
// ============================================================

// PLACEHOLDER: Replace this with the actual server public key
// generated by relay/setup_keys.py. Until then, auth signature
// verification will fail (which is correct — you should not trust
// an unconfigured server).
   
const unsigned char SERVER_ED25519_PUBKEY[32] = {        
    0xc5, 0x60, 0x78, 0x55, 0xd7, 0x5a, 0xd1, 0x41,
    0xe1, 0x21, 0xdb, 0xae, 0xb7, 0x8d, 0x06, 0xea,
    0xac, 0x65, 0x48, 0x90, 0x24, 0x39, 0x2c, 0x4b,
    0x68, 0x80, 0x96, 0x45, 0x05, 0xc9, 0x21, 0x51
};  

// ============================================================
// libcurl write callback
// ============================================================

static size_t write_cb(void* contents, size_t size, size_t nmemb, void* userp) {
    size_t total = size * nmemb;
    std::string* response = static_cast<std::string*>(userp);
    response->append(static_cast<char*>(contents), total);
    return total;
}

// ============================================================
// Tor HTTP helpers
// ============================================================

std::string tor_post(const std::string& url, const std::string& json_payload) {
    CURL* curl = curl_easy_init();
    if (!curl) {
        std::cerr << "[-] curl_easy_init() failed\n";
        return "";
    }

    std::string response;

    // Only route through Tor if it's an onion service
    if (url.find(".onion") != std::string::npos) {
        curl_easy_setopt(curl, CURLOPT_PROXY, "socks5h://127.0.0.1:9050");
    }
    
    curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, json_payload.c_str());
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_cb);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30L);

    struct curl_slist* headers = nullptr;
    headers = curl_slist_append(headers, "Content-Type: application/json");
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

    CURLcode res = curl_easy_perform(curl);
    curl_slist_free_all(headers);
    curl_easy_cleanup(curl);

    if (res != CURLE_OK) {
        std::cerr << "[-] Tor POST failed: " << curl_easy_strerror(res) << "\n";
        return "";
    }

    return response;
}

std::string tor_get(const std::string& url) {
    CURL* curl = curl_easy_init();
    if (!curl) {
        std::cerr << "[-] curl_easy_init() failed\n";
        return "";
    }

    std::string response;

    // Only route through Tor if it's an onion service
    if (url.find(".onion") != std::string::npos) {
        curl_easy_setopt(curl, CURLOPT_PROXY, "socks5h://127.0.0.1:9050");
    }

    curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_cb);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30L);

    CURLcode res = curl_easy_perform(curl);
    curl_easy_cleanup(curl);

    if (res != CURLE_OK) {
        std::cerr << "[-] Tor GET failed: " << curl_easy_strerror(res) << "\n";
        return "";
    }

    return response;
}

// ============================================================
// Platform-specific password input (no echo)
// ============================================================

static std::string read_password() {
    std::string password;

#ifdef _WIN32
    // Windows: use ReadConsole with echo disabled
    HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE);
    DWORD mode;
    GetConsoleMode(hStdin, &mode);
    SetConsoleMode(hStdin, mode & ~ENABLE_ECHO_INPUT);

    std::getline(std::cin, password);

    SetConsoleMode(hStdin, mode); // restore
    std::cout << "\n"; // newline since echo was off
#else
    // POSIX: toggle termios echo
    struct termios oldt, newt;
    tcgetattr(STDIN_FILENO, &oldt);
    newt = oldt;
    newt.c_lflag &= ~ECHO;
    tcsetattr(STDIN_FILENO, TCSANOW, &newt);

    std::getline(std::cin, password);

    tcsetattr(STDIN_FILENO, TCSANOW, &oldt);
    std::cout << "\n";
#endif

    return password;
}

// ============================================================
// PasswordLogin implementation
// ============================================================

void PasswordLogin::prompt_credentials() {
    std::cout << "Username: ";
    std::getline(std::cin, username_);

    std::cout << "Password: ";
    std::string password = read_password();

    // Compute SHA-256(password + username) — raw password never leaves device
    std::string combined = password + username_;
    credential_hash_ = sha256_hash(combined);

    // Wipe the raw password from memory immediately
    secure_wipe(&password[0], password.size());
    secure_wipe(&combined[0], combined.size());
}

std::vector<unsigned char> PasswordLogin::get_credential_hash() {
    return credential_hash_;
}

std::string PasswordLogin::get_username() const {
    return username_;
}

bool PasswordLogin::authenticate(const std::string& server_url) {
    prompt_credentials();

    // Build auth payload
    json auth_payload;
    auth_payload["username"] = username_;

    // Base64-encode the credential hash for transport
    size_t b64_maxlen = sodium_base64_ENCODED_LEN(
        credential_hash_.size(), sodium_base64_VARIANT_ORIGINAL);
    std::string hash_b64(b64_maxlen, '\0');
    sodium_bin2base64(&hash_b64[0], b64_maxlen,
                      credential_hash_.data(), credential_hash_.size(),
                      sodium_base64_VARIANT_ORIGINAL);
    hash_b64.resize(strlen(hash_b64.c_str()));

    auth_payload["credential_hash"] = hash_b64;

    std::string url = server_url + "/auth";
    std::cout << "[*] Authenticating with server...\n";

    std::string response = tor_post(url, auth_payload.dump());
    if (response.empty()) {
        std::cerr << "[-] Authentication failed — no response from server\n";
        return false;
    }

    // Parse server response
    try {
        json resp = json::parse(response);

        if (!resp.contains("status") || resp["status"] != "ok") {
            std::cerr << "[-] Authentication failed: "
                      << resp.value("message", "unknown error") << "\n";
            return false;
        }

        // Verify Ed25519 signature on the response
        if (resp.contains("signature") && resp.contains("payload")) {
            std::string sig_b64 = resp["signature"].get<std::string>();
            std::string payload = resp["payload"].get<std::string>();

            // Decode the signature
            std::vector<unsigned char> sig(sig_b64.size());
            size_t sig_len = 0;
            if (sodium_base642bin(sig.data(), sig.size(),
                                  sig_b64.c_str(), sig_b64.size(),
                                  nullptr, &sig_len, nullptr,
                                  sodium_base64_VARIANT_ORIGINAL) != 0) {
                std::cerr << "[-] Failed to decode server signature\n";
                return false;
            }
            sig.resize(sig_len);

            // Verify against the hardcoded server public key
            bool valid = ed25519_verify_detached(
                sig.data(),
                reinterpret_cast<const unsigned char*>(payload.data()),
                payload.size(),
                SERVER_ED25519_PUBKEY
            );

            if (!valid) {
                std::cerr << "[-] CRITICAL: Server signature verification FAILED\n";
                std::cerr << "    Possible MITM attack — aborting authentication\n";
                return false;
            }
            std::cout << "[+] Server Ed25519 signature verified\n";

            auth_token_ = payload;
            auth_signature_ = sig_b64;
        }

        authenticated_ = true;
        std::cout << "[+] Authentication successful\n";
        return true;

    } catch (const json::exception& e) {
        std::cerr << "[-] Failed to parse auth response: " << e.what() << "\n";
        return false;
    }
}

bool PasswordLogin::register_account(const std::string& server_url) {
    prompt_credentials();

    json reg_payload;
    reg_payload["username"] = username_;

    // Base64-encode the credential hash
    size_t b64_maxlen = sodium_base64_ENCODED_LEN(
        credential_hash_.size(), sodium_base64_VARIANT_ORIGINAL);
    std::string hash_b64(b64_maxlen, '\0');
    sodium_bin2base64(&hash_b64[0], b64_maxlen,
                      credential_hash_.data(), credential_hash_.size(),
                      sodium_base64_VARIANT_ORIGINAL);
    hash_b64.resize(strlen(hash_b64.c_str()));

    reg_payload["credential_hash"] = hash_b64;

    std::string url = server_url + "/register";
    std::cout << "[*] Registering account...\n";

    std::string response = tor_post(url, reg_payload.dump());
    if (response.empty()) {
        std::cerr << "[-] Registration failed — no response from server\n";
        return false;
    }

    try {
        json resp = json::parse(response);
        if (resp.contains("status") && resp["status"] == "ok") {
            std::cout << "[+] Registration successful\n";
            return true;
        } else {
            std::cerr << "[-] Registration failed: "
                      << resp.value("message", "unknown error") << "\n";
            return false;
        }
    } catch (const json::exception& e) {
        std::cerr << "[-] Failed to parse registration response: " << e.what() << "\n";
        return false;
    }
}

bool PasswordLogin::upload_public_keys(const std::string& server_url, const std::string& public_keys_json) {
    if (!authenticated_ || auth_token_.empty() || auth_signature_.empty()) {
        std::cerr << "[-] Cannot upload keys: not authenticated\n";
        return false;
    }

    json upload_payload;
    upload_payload["payload"] = auth_token_;
    upload_payload["signature"] = auth_signature_;
    upload_payload["public_keys"] = public_keys_json;

    std::string url = server_url + "/upload_key";
    std::cout << "[*] Uploading public keys to Key Server...\n";

    std::string response = tor_post(url, upload_payload.dump());
    if (response.empty()) return false;

    try {
        json resp = json::parse(response);
        if (resp.contains("status") && resp["status"] == "ok") {
            std::cout << "[+] Public keys successfully published to Key Server\n";
            return true;
        } else {
            std::cerr << "[-] Key upload failed: " << resp.value("message", "unknown") << "\n";
            return false;
        }
    } catch (...) {
        return false;
    }
}

std::string PasswordLogin::fetch_public_keys(const std::string& server_url, const std::string& target_username) {
    std::string url = server_url + "/get_key/" + target_username;
    std::string response = tor_get(url);
    if (response.empty()) return "";

    try {
        json resp = json::parse(response);
        if (resp.contains("status") && resp["status"] == "ok") {
            return resp["public_keys"].get<std::string>();
        }
    } catch (...) {}
    return "";
}

// Utility for hex
static std::string bin_to_hex(const unsigned char* data, size_t len) {
    std::string hex_chars = "0123456789abcdef";
    std::string out;
    for (size_t i = 0; i < len; ++i) {
        out += hex_chars[data[i] >> 4];
        out += hex_chars[data[i] & 0x0f];
    }
    return out;
}

static bool hex_to_bin(const std::string& hex, std::vector<unsigned char>& out) {
    if (hex.size() % 2 != 0) return false;
    out.resize(hex.size() / 2);
    for (size_t i = 0; i < out.size(); ++i) {
        unsigned int byte;
        std::istringstream iss(hex.substr(i * 2, 2));
        iss >> std::hex >> byte;
        if (iss.fail()) return false;
        out[i] = static_cast<unsigned char>(byte);
    }
    return true;
}

bool PasswordLogin::save_identity(const HybridKeyPair& keypair, const std::string& filepath) {
    if (credential_hash_.empty()) return false;

    // Serialize keypair to JSON
    json j;
    j["x25519_private"] = bin_to_hex(keypair.x25519_private, 32);
    j["x25519_public"] = bin_to_hex(keypair.x25519_public, 32);
    j["kyber_private"] = bin_to_hex(keypair.kyber_private.data(), keypair.kyber_private.size());
    j["kyber_public"] = bin_to_hex(keypair.kyber_public.data(), keypair.kyber_public.size());
    
    std::string plaintext = j.dump();

    // Encrypt using credential hash as the symmetric key
    EncryptedMessage enc = encrypt_message(plaintext, credential_hash_.data(), 8192);
    std::string encrypted_json = encrypted_to_json(enc);

    std::ofstream out(filepath, std::ios::binary);
    if (!out) return false;
    out << encrypted_json;
    return true;
}

bool PasswordLogin::load_identity(HybridKeyPair& keypair, const std::string& filepath) {
    if (credential_hash_.empty()) return false;

    std::ifstream in(filepath, std::ios::binary);
    if (!in) return false; // File doesn't exist
    std::stringstream buffer;
    buffer << in.rdbuf();

    EncryptedMessage enc = json_to_encrypted(buffer.str());
    if (enc.ciphertext.empty()) return false;

    std::string plaintext = decrypt_message(enc, credential_hash_.data());
    if (plaintext.empty()) return false; // Wrong password

    try {
        json j = json::parse(plaintext);
        
        std::vector<unsigned char> temp;
        if (!hex_to_bin(j["x25519_private"].get<std::string>(), temp) || temp.size() != 32) return false;
        std::memcpy(keypair.x25519_private, temp.data(), 32);

        if (!hex_to_bin(j["x25519_public"].get<std::string>(), temp) || temp.size() != 32) return false;
        std::memcpy(keypair.x25519_public, temp.data(), 32);

        if (!hex_to_bin(j["kyber_private"].get<std::string>(), keypair.kyber_private)) return false;
        if (!hex_to_bin(j["kyber_public"].get<std::string>(), keypair.kyber_public)) return false;
        
        return true;
    } catch (...) {
        return false;
    }
}

